# Generated by Django 5.0.6 on 2024-05-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('PKG', 'pkg'), ('LB', 'lb'), ('OZ', 'oz'), ('GAL', 'gal')], default='PKG', max_length=50),
        ),
    ]
