# Generated by Django 5.0.6 on 2024-05-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_amount_ingredient_quantity_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('PKG', 'pkg'), ('LB', 'lb'), ('OZ', 'oz'), ('GAL', 'gal'), ('UNITS', 'units')], default='UNITS', max_length=50),
        ),
    ]
